### GENERAL SETTINGS ###

# Site settings
title: ALEX STROUD
description: "Junior Games Development Graduate."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/" #important: start with /
url: "https://Stroudie2.github.io"
# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: false
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://www.facebook.com/alex.stroud.988
  - title: twitter
    url:
  - title: instagram
    url: https://www.instagram.com/alex_stroud97/
  - title: linkedin
    url: https://www.linkedin.com/in/alex-stroud-47751b150

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Basingstoke,
    - Hampshire, RG22 4PJ,
    - United Kingdom.
email: alexjamesstroud@gmail.com

include:
  - "img"

### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Alex Stroud
    position: BSc Hons Graduate In Games Technology
    text: I am a keen and passionate games developer, whose love of programming extends to mentoring others to allow them to develop games for themselves.
    img: profile_1.jpg
    social:
      - title: envelope #use for email address
        url: mailto:alexjamesstroud@gmail.com
      - title: twitter
        url: http://twitter.com/
 
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Junior Games Technology Graduate."
